language: python

notifications:
  email:
    recipients:
      - lyyyuna@outlook.com
      - 1546331221@qq.com
    on_success: always
    on_failure: always

python:
  - "3.5"

before_install:
  - cd lihulaboj
  - export DJANGO_SETTINGS_MODULE=lihulaboj.settings.unittest

install:
  - pip install django --quiet
  - pip install djangorestframework --quiet
  - pip install coveralls --quiet
  - pip install psycopg2 --quiet
  - pip install celery --quiet

script: 
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=./ manage.py test --pattern="test_*.py"

after_success:
  - coveralls