version: '2'

services:
  db:
    image: postgres:9.5
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: /bin/sh -c "sleep 10 && 
                          cd lihulaboj && 
                          python manage.py makemigrations && 
                          python manage.py migrate && 
                          python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
