version: '2'

services:
  db:
    image: postgres:9.5
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    environment:
      - DJANGO_SETTINGS_MODULE=lihulaboj.settings.development
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@admin.com
    command: /bin/sh -c "sleep 10 && 
                          cd lihulaboj && 
                          python manage.py makemigrations&& 
                          python manage.py migrate&& 
                          python manage.py addadmin&&
                          python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  redis:
    image: redis
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=lihulaboj.settings.development
      - JUDGE_TOKEN=YOUR_TOKEN_HERE
      - JUDGE_SERVER_IP=10.64.54.60
      - JUDGE_SERVER_PORT=12358
    command: /bin/sh -c 'sleep 10 &&
                        cd lihulaboj &&
                        su -m myuser -c "celery -A lihulaboj worker -l info"'
    volumes:
      - .:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis