# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answser',
            name='result',
            field=models.CharField(choices=[('N/A', 'N/A'), ('WRONG_ANSWER', 'WRONG_ANSWER'), ('SUCCESS', 'SUCCESS'), ('CPU_TIME_LIMIT_EXCEEDED', 'CPU_TIME_LIMIT_EXCEEDED'), ('REAL_TIME_LIMIT_EXCEEDED', 'REAL_TIME_LIMIT_EXCEEDED'), ('MEMORY_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED'), ('RUNTIME_ERROR', 'RUNTIME_ERROR'), ('SYSTEM_ERROR', 'SYSTEM_ERROR')], max_length=200),
        ),
    ]
