# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20171013_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answser',
            name='result',
            field=models.TextField(default='error'),
        ),
        migrations.AlterField(
            model_name='answser',
            name='source_code',
            field=models.TextField(default='error'),
        ),
    ]
