# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20171013_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answser',
            name='real_time',
        ),
        migrations.AddField(
            model_name='answser',
            name='cpu_time',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='problem',
            name='input1',
            field=models.TextField(default='error'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input2',
            field=models.TextField(default='error'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output1',
            field=models.TextField(default='error'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output2',
            field=models.TextField(default='error'),
        ),
        migrations.AlterField(
            model_name='answser',
            name='memory',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='problem',
            name='max_cpu_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='problem',
            name='max_memory',
            field=models.IntegerField(default=64),
        ),
    ]
