# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20171014_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='error', unique=True),
        ),
    ]
