# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20171015_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pass_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
    ]
