# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20171016_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answser',
            name='cpu_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answser',
            name='language',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answser',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answser',
            name='result',
            field=models.IntegerField(default=-1),
        ),
    ]
