# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojproblem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojuseransweraggr',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='ojuseransweraggr',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ojproblem.OJAnswer'),
        ),
        migrations.AddField(
            model_name='ojuseransweraggr',
            name='cpu',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ojuseransweraggr',
            name='memory',
            field=models.IntegerField(default=-1),
        ),
    ]
