# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojproblem', '0003_auto_20180725_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojanswer',
            name='source_code',
            field=models.TextField(max_length=2048),
        ),
    ]
