# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojproblem', '0006_auto_20180726_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojanswer',
            name='result',
            field=models.IntegerField(default=-10),
        ),
    ]
