# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170504_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failedproblem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passproblem',
            field=models.IntegerField(default=0),
        ),
    ]
