# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170508_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='failedproblem',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passproblem',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
