# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojuserprofile',
            name='pass_num',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ojuserprofile',
            name='total_num',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
