# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojuser', '0002_auto_20180725_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiationcode',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
