# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ojuser', '0003_activiationcode_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojuserprofile',
            name='last_submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ojuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojuserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
