name: Online Judger Integratoin Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "django<2" --quiet
        pip install djangorestframework --quiet
        pip install coveralls --quiet
        pip install psycopg2-binary --quiet
        pip install celery --quiet
        pip install django-cors-headers --quiet
    - name: Test
      run: |
        cd OnlineJudge
        export DJANGO_SETTINGS_MODULE=oj.settings.unittest
        python manage.py makemigrations
        python manage.py migrate
        coverage run --source=./ manage.py test --pattern="test_*.py"
        coveralls
